name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: RUSTFLAGS="-Z threads=4" cargo +nightly build --future-incompat-report && cargo clippy
#    - name: Run tests
#      run: cargo test --verbose
